Fix install path for fortran module and export name
mutationpp/Mutationpp pull request #178
Opened 2021-09-21 22:52 UTC by rubendibattista

The example CMakeLists for the fortran interface was not working outside
of the Mutation++ build tree because the only target exported was named
`mutation++_fortran` and not `mutation++::fortran_interface` as shown in
the CMakeLists.txt.shared in interface/fortran. Now it's fixed

Also the Fortran module file was installed in the wrong include dir

2021-09-21 23:33 UTC, rubendibattista commented
(Also release 1.0.6 such that I can upload also the Macports port)

2021-09-24 14:16 UTC, jbscoggi requested changes
Hey @rubendibattista, I think the last version was actually 1.1.0 so the new version needs to be 1.1.1, not 1.0.6.  If you make this change and the tests pass, we can definitely merge.

2021-11-02 23:23 UTC, rubendibattista commented
Bump! :)

2021-11-04 01:57 UTC, merged

2021-11-04 01:57 UTC, jbscoggi commented
Thanks @rubendibattista!